### PR TITLE
setup new smtp for mailing

### PR DESCRIPTION
**Pull request by johnayinde**

### CODE REVIEW

**Review by hayzedDev — COMMENTED** [review]
you should also update the .env.example file with the new configs

Also email validator should also be added to sendEmailDTO

**Comment by johnayinde** [comment]
> you should also update the .env.example file with the new configs
> 
> Also email validator should also be added to sendEmailDTO

 it exists already, You can check the env.example file for the env variables names

 Email already passed through validation on identity service that is sending in a request to this service

**Comment by hayzedDev** [comment]
> > you should also update the .env.example file with the new configs
> > Also email validator should also be added to sendEmailDTO
> 
> it exists already, You can check the env.example file for the env variables names
> 
> Email already passed through validation on identity service that is sending in a request to this service

Okay

Also, why did you name the author Zummit Dummy APP?
WhatsApp Image 2023-03-21 at 11 46 13

**Comment by hayzedDev** [comment]
Also, I was thinking if we can add more UI to the email. That would be great

We can use any of the email template online

**Comment by johnayinde** [comment]
> Also, why did you name the author Zummit Dummy APP? WhatsApp Image 2023-03-21 at 11 46 13


That’s what we have on development, the env variable responsible for that changes on other environment

**Comment by johnayinde** [comment]
> Also, I was thinking if we can add more UI to the email.

that’s another feature that’s different from this PR you can communicate that to the team lead

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
